# Generated by Django 5.2.3 on 2025-07-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_matricula_costo_alter_estudiante_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='costo',
            field=models.IntegerField(),
        ),
    ]
